In [ ]:
import numpy as np
from model.camera_model import CameraModel
from calib.preprocess import Preprocess
from pathlib import Path

CCD = 'IMX477'
fisheye = False
operation_folder = '0617_IMX477_5000'
CHECKERBOARD = (8,11)

In [2]:

cam_path = Path("datasets") / 'calibration_data' / "single_no fix.npz"
camera = CameraModel.load_model(cam_path)
print(camera)

Loading camera model at datasets\calibration_data\single_no fix.npz

CCD_type = IMX477
image_size = (4056, 3040)
is_fisheye = False
cm1: 
 [[3.99239162e+03 0.00000000e+00 1.87767550e+03]
 [0.00000000e+00 3.99221399e+03 1.60518955e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd1: 
 [[-5.08339339e-01  3.53270516e-01 -2.37038484e-04 -7.70688493e-05
  -1.78475147e-01]]
cm2: 
 [[3.98387812e+03 0.00000000e+00 1.96713890e+03]
 [0.00000000e+00 3.98519784e+03 1.48114130e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd2: 
 [[-5.05135618e-01  3.61614451e-01 -2.37092619e-04  1.66236206e-03
  -1.95622931e-01]]
R: 
 [[ 0.99998418  0.00268304  0.00494291]
 [-0.00265584  0.99998134 -0.00550201]
 [-0.00495758  0.0054888   0.99997265]]
T: 
 [[-2.00553226e+02]
 [ 1.43538455e+00]
 [ 1.90726804e-01]]


In [1]:
cam_path = Path("datasets") / 'calibration_data' / "sbs_no fix.npz"
camera = CameraModel.load_model(cam_path)
print(camera)

Loading camera model at datasets\calibration_data\sbs_no fix.npz

CCD_type = IMX477
image_size = (4056, 3040)
is_fisheye = False
cm1: 
 [[3.99239583e+03 0.00000000e+00 1.87765520e+03]
 [0.00000000e+00 3.99221781e+03 1.60518512e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd1: 
 [[-5.08339677e-01  3.53268800e-01 -2.36867781e-04 -7.61515037e-05
  -1.78474014e-01]]
cm2: 
 [[3.98388009e+03 0.00000000e+00 1.96711493e+03]
 [0.00000000e+00 3.98520130e+03 1.48113687e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd2: 
 [[-5.05134627e-01  3.61608486e-01 -2.36934542e-04  1.66342454e-03
  -1.95609438e-01]]
R: 
 [[ 0.99998418  0.00268319  0.00494372]
 [-0.00265599  0.99998134 -0.00550196]
 [-0.00495839  0.00548874  0.99997264]]
T: 
 [[-2.00553096e+02]
 [ 1.43535803e+00]
 [ 1.91560305e-01]]


In [3]:
cam_path = Path("datasets") / 'calibration_data' / "single_fix.npz"
camera = CameraModel.load_model(cam_path)
print(camera)

Loading camera model at datasets\calibration_data\single_fix.npz

CCD_type = IMX477
image_size = (4056, 3040)
is_fisheye = False
cm1: 
 [[3.99211496e+03 0.00000000e+00 1.87258128e+03]
 [0.00000000e+00 3.99151265e+03 1.56850368e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd1: 
 [[-5.03400347e-01  3.39021374e-01  1.65040883e-03  2.94987255e-04
  -1.72542792e-01]]
cm2: 
 [[3.98314073e+03 0.00000000e+00 1.98184583e+03]
 [0.00000000e+00 3.98654253e+03 1.45900661e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd2: 
 [[-4.97028947e-01  3.17328782e-01  6.47311729e-04  2.60749341e-04
  -1.45258983e-01]]
R: 
 [[ 0.99999086  0.00329459  0.00272497]
 [-0.00327128  0.99995838 -0.00851666]
 [-0.00275292  0.00850767  0.99996002]]
T: 
 [[-2.03442991e+02]
 [ 8.50327406e-01]
 [ 1.80709802e-01]]


In [4]:
cam_path = Path("datasets") / 'calibration_data' / "sbs_fix.npz"
camera = CameraModel.load_model(cam_path)
print(camera)

Loading camera model at datasets\calibration_data\sbs_fix.npz

CCD_type = IMX477
image_size = (4056, 3040)
is_fisheye = False
cm1: 
 [[3.98697789e+03 0.00000000e+00 1.86255973e+03]
 [0.00000000e+00 3.98601323e+03 1.59688060e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd1: 
 [[-5.00607579e-01  3.17047642e-01  1.02962603e-04  9.61176514e-04
  -1.34807805e-01]]
cm2: 
 [[3.98020696e+03 0.00000000e+00 1.97757426e+03]
 [0.00000000e+00 3.98107462e+03 1.47896477e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
cd2: 
 [[-4.99436036e-01  3.31475224e-01 -1.75516147e-04  9.31090527e-04
  -1.52601547e-01]]
R: 
 [[ 9.99995744e-01  2.79149089e-03  8.48117037e-04]
 [-2.78557476e-03  9.99972325e-01 -6.89849515e-03]
 [-8.67350652e-04  6.89610330e-03  9.99975845e-01]]
T: 
 [[-2.02991135e+02]
 [ 1.28082536e+00]
 [ 1.87389575e-01]]
